### ISSUE TITLE
[19:35:11 ERROR]: Could not pass event PlayerQuitEvent to ResourceWorld v1.9.3

### ISSUE THREAD

**Issue by wattywatty14** [NikV2/ResourceWorld#11] opened 2021-01-28 00:36 UTC
This happens every time I quit my server:
https://pastebin.com/8xz7KT0T

**Comment by NikV2** [comment] 2021-01-28 00:49
Do a complete reset on your config.yml, or try to manually put your main world in the main_world section. let me know if that fixes it.

**Comment by wattywatty14** [comment] 2021-01-28 21:49
I did both. it doesn't solve the issue.

**Comment by NikV2** [comment] 2021-01-28 23:01
Sorry i'm not able to reproduce the error, Make sure there are no typos inside the config. I'll close this issue for now.

**Closed by NikV2** 2021-01-28 23:01 UTC
